### ISSUE TITLE
retirer le chapitre Architecture Overvien et mettre la version 0.0.1 en haut a gauche

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-documentation#14]
Documenttaion 0.0.1
![Capture d’écran de 2024-10-09 13-27-04](https://github.com/user-attachments/assets/5cce28bf-68cf-4b14-9bd6-72889e64a0c6)

**Comment by BastienLopez** [comment]
https://github.com/TalaoDAO/talao-documentation/commit/634f38c9e262ea700db10bf9a8753ee7ccc25c76

**Comment by BastienLopez** [comment]
https://github.com/TalaoDAO/talao-documentation/pull/16
