### ISSUE TITLE
Ajouter une page apres wallet technical features et avnat FAQ  : Wallet metadata 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/talao-documentation#2]
Ajouter les valeurs les fichiers ci dessous sous forme de code
[wallet_metadata_for_issuer.json](https://github.com/user-attachments/files/17283995/wallet_metadata_for_issuer.json)
[wallet_metadata_for_verifiers.json](https://github.com/user-attachments/files/17283996/wallet_metadata_for_verifiers.json)

**Comment by BastienLopez** [comment]
https://github.com/TalaoDAO/talao-documentation/pull/9
